const { LOST_ITEM_STATUS, FOUND_ITEM_STATUS, CLAIM_STATUS } = require('./constants');

const LOST_TRANSITIONS = {
  [LOST_ITEM_STATUS.DRAFT]: [LOST_ITEM_STATUS.PUBLISHED, LOST_ITEM_STATUS.ARCHIVED],
  [LOST_ITEM_STATUS.PUBLISHED]: [LOST_ITEM_STATUS.MATCH_FOUND, LOST_ITEM_STATUS.CLAIM_PENDING, LOST_ITEM_STATUS.CLOSED, LOST_ITEM_STATUS.EXPIRED, LOST_ITEM_STATUS.RESOLVED],
  [LOST_ITEM_STATUS.MATCH_FOUND]: [LOST_ITEM_STATUS.CLAIM_PENDING, LOST_ITEM_STATUS.PUBLISHED, LOST_ITEM_STATUS.CLOSED, LOST_ITEM_STATUS.RESOLVED],
  [LOST_ITEM_STATUS.CLAIM_PENDING]: [LOST_ITEM_STATUS.RETURNED, LOST_ITEM_STATUS.PUBLISHED, LOST_ITEM_STATUS.CLOSED, LOST_ITEM_STATUS.RESOLVED],
  [LOST_ITEM_STATUS.RETURNED]: [LOST_ITEM_STATUS.RESOLVED, LOST_ITEM_STATUS.CLOSED],
  [LOST_ITEM_STATUS.RESOLVED]: [LOST_ITEM_STATUS.ARCHIVED],
  [LOST_ITEM_STATUS.CLOSED]: [LOST_ITEM_STATUS.ARCHIVED],
  [LOST_ITEM_STATUS.EXPIRED]: [LOST_ITEM_STATUS.PUBLISHED, LOST_ITEM_STATUS.ARCHIVED],
  [LOST_ITEM_STATUS.ARCHIVED]: []
};

const FOUND_TRANSITIONS = {
  [FOUND_ITEM_STATUS.DRAFT]: [FOUND_ITEM_STATUS.PUBLISHED, FOUND_ITEM_STATUS.ARCHIVED],
  [FOUND_ITEM_STATUS.PUBLISHED]: [FOUND_ITEM_STATUS.MATCH_FOUND, FOUND_ITEM_STATUS.CLAIM_PENDING, FOUND_ITEM_STATUS.CLOSED, FOUND_ITEM_STATUS.RESOLVED],
  [FOUND_ITEM_STATUS.MATCH_FOUND]: [FOUND_ITEM_STATUS.CLAIM_PENDING, FOUND_ITEM_STATUS.VERIFICATION, FOUND_ITEM_STATUS.PUBLISHED, FOUND_ITEM_STATUS.CLOSED, FOUND_ITEM_STATUS.RESOLVED],
  [FOUND_ITEM_STATUS.CLAIM_PENDING]: [FOUND_ITEM_STATUS.VERIFICATION, FOUND_ITEM_STATUS.HANDED_OVER, FOUND_ITEM_STATUS.PUBLISHED, FOUND_ITEM_STATUS.CLOSED, FOUND_ITEM_STATUS.RESOLVED],
  [FOUND_ITEM_STATUS.VERIFICATION]: [FOUND_ITEM_STATUS.HANDED_OVER, FOUND_ITEM_STATUS.CLAIM_PENDING, FOUND_ITEM_STATUS.PUBLISHED],
  [FOUND_ITEM_STATUS.HANDED_OVER]: [FOUND_ITEM_STATUS.RETURNED, FOUND_ITEM_STATUS.RESOLVED],
  [FOUND_ITEM_STATUS.RETURNED]: [FOUND_ITEM_STATUS.RESOLVED],
  [FOUND_ITEM_STATUS.RESOLVED]: [FOUND_ITEM_STATUS.ARCHIVED],
  [FOUND_ITEM_STATUS.CLOSED]: [FOUND_ITEM_STATUS.ARCHIVED],
  [FOUND_ITEM_STATUS.ARCHIVED]: []
};

function isValidStateTransition(type, currentStatus, nextStatus) {
  if (currentStatus === nextStatus) return true;
  const transitions = type === 'lost' ? LOST_TRANSITIONS : FOUND_TRANSITIONS;
  const allowed = transitions[currentStatus] || [];
  return allowed.includes(nextStatus);
}

module.exports = {
  LOST_TRANSITIONS,
  FOUND_TRANSITIONS,
  isValidStateTransition,
};
